twig:
  default_path: "%kernel.project_dir%/templates"
  debug: "%kernel.debug%"
  strict_variables: "%kernel.debug%"
  form_themes:
    [
      "form/letrading_layout.html.twig",
      "@FOSCKEditor/Form/ckeditor_widget.html.twig",
    ]
  globals:
    isGranted: '@App\Service\GrantedService'
